# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Azure Web App - EdgarConnector

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: './frontend/package.json'

      - name: Install and Build React Frontend
        run: |
          cd frontend
          npm cache clean --force
          npm install
          npm run build

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Create wwwroot directory
        run: |
          if (!(Test-Path "ApiGraphActivator/wwwroot")) {
            New-Item -ItemType Directory -Path "ApiGraphActivator/wwwroot" -Force
          }
        shell: pwsh

      - name: Copy React build to wwwroot
        run: |
          Copy-Item -Path "frontend/build/*" -Destination "ApiGraphActivator/wwwroot/" -Recurse -Force
        shell: pwsh

      - name: Restore .NET dependencies
        run: dotnet restore ApiGraphActivator/ApiGraphActivator.csproj

      - name: Build with dotnet
        run: dotnet build ApiGraphActivator/ApiGraphActivator.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish ApiGraphActivator/ApiGraphActivator.csproj -c Release -o "./publish"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_995610E4B41F4E6FA831DF928041ED84 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A79985650572425BB30AEF249A39F362 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2246E411E4B74AAA974C8B642D35D452 }}

      - name: Configure Azure App Service Settings
        run: |
          az webapp config appsettings set --name EdgarConnector --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings `
            "ASPNETCORE_ENVIRONMENT=Production" `
            "TableStorage=${{ secrets.TABLE_STORAGE }}" `
            "CompanyTableName=trackedCompanies" `
            "ProcessedTableName=processedFormsText" `
            "BlobContainerName=${{ secrets.BLOB_CONTAINER_NAME }}" `
            "APPLICATIONINSIGHTS_CONNECTION_STRING=${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}" `
            "EmailAddress=${{ secrets.EMAIL_ADDRESS }}" `
            "AzureAd__ClientId=${{ secrets.AZUREAD_CLIENT_ID }}" `
            "AzureAd__ClientSecret=${{ secrets.AZUREAD_CLIENT_SECRET }}" `
            "AzureAd__TenantId=${{ secrets.AZUREAD_TENANT_ID }}"
        shell: pwsh

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'EdgarConnector'
          slot-name: 'Production'
          package: .
          